name: Pull Request Workflow Local

on:
  pull_request:
    branches: 
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - name: Pull Request
        run: echo "There was a pull request"
