name: Pull Request Workflow Local

on:
  pull_request:
    branches: 
      - main
jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Pull Request Trigger
        run: echo "Pull Request was triggered"
