name: Schefuled Workflow

on:
  schedule:
    - cron: '*/5 * * * * *'
      
jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Schedule Trigger
        run: echo "Scheduled every 5 minutes"
