name: Scheduled Workflow Local

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:    
      
jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Schedule Trigger
        run: echo "Scheduled every 5 minutes"
